### PR TITLE
Feature/seq support

### PR DESCRIPTION
**Pull request by corvaxx**
SEQ support (and coins with timestamp in transaction, like ppcoin and old bitcoin)
code prepared for support non-secp256k1 coins
role field removed from xbridge protocol

### CODE REVIEW

**Comment by magic53** [comment]
@corvaxx need your help, can you put your changes on top of base branch 3.9.16 without merge commits? bad code in fix-orderbook-inconsistencies 3.9.17 3.9.18-dev

**Comment by corvaxx** [comment]
Ок

**Comment by magic53** [comment]
Also 👍 to request PR merge into 3.9.18

**Comment by corvaxx** [comment]
rebased

**Comment by magic53** [comment]
new one looks good. 

base branch for work is release branch 3.9.16 in case other branches get removed (like 3.9.17 was removed), then PR request into next release 3.9.18

**Comment by magic53** [comment]
we will put in 3.9.18-dev for testing

**Pull request closed without merging**
