### PR TITLE
remove upper limit on address

### PR DESCRIPTION
**Pull request by atcsecure**
required for ETH

### CODE REVIEW

**Comment by corvaxx** [comment]
each connector class must have functions for address validation
i think in this case it is better to use it

**Comment by atcsecure** [comment]
@corvaxx Ok, I will review each connector

**Comment by magic53** [comment]
`validateaddress` is doing this, technically this func isn't required, but it's faster to do simple check first than to make rpc calls that are expensive

**Comment by corvaxx** [comment]
legacy, segwit, bech32, ethereum...this one simple rule for all addresses?
for example, the address of the block testnet may be valid for the main litecoin network and this is a big problem :) (see BtcWalletConnector::toXAddr)
and validateaddress rpc call for ethereum...

**Comment by magic53** [comment]
We're all in agreement. It can all be handled in our validate address func, for each chain, no need for `App::isValidAddress`

**Comment by corvaxx** [comment]
image
i think this is invalid behavior. but this order can be created successfully, because isValidAddress() is very simple

**Pull request merged**
