### PR TITLE
Feat/side bar

### PR DESCRIPTION
**Pull request by SuperSkyDeveloper**

### CODE REVIEW

**Comment by sh-rn** [comment]
@SuperSkyDeveloper when testing I notice that the styling of the sidebar doesn't match the design. eg margins/paddings, colours, and the width aren't the same as in zeplin. There are also some similar items on the modules themselves. I can provide exact details but it might be better if you can compare the modules with the design first?

Overall, it's looking good though and thanks for delivering the component quickly.

**Comment by SuperSkyDeveloper** [comment]
@shrnkld, I'll fix it

**Comment by sh-rn** [comment]
Looking good but a few more minor issues to fix (as discussed already in Discord) ...

1. pls maintain a consistent margin of 2px between all modules 
2. check font sizes (titles and content) compared to design in zeplin
3. sidebar bottom nav menu is cutoff - should be at a fixed position at the bottom of the viewport 
Screenshot 2023-03-20 at 16 46 42
Screenshot 2023-03-20 at 16 42 04
Screenshot 2023-03-20 at 16 42 19

**Comment by SuperSkyDeveloper** [comment]
Let me fix them

**Pull request merged**
