### PR TITLE
Added fallback for gettxout rpc method

### PR DESCRIPTION
**Pull request by Lazark0x**

### CODE REVIEW

**Comment by corvaxx** [comment]
gettxout can not be fully replaced with gettransaction, because it only works for in-wallet ransactions

**Comment by corvaxx** [comment]
why this approved?
gettxout can NOT be replaced with get(raw)transaction
these are completely different methods by logic
and getrawtransaction already implemented in other place, this is a spaghetti-style

**Comment by DanielZorin** [comment]
What is the difference and how do you suggest to deal with the chains that don't have gettxout then?

**Comment by corvaxx** [comment]
> getrawtransaction works for all transactions, not only for in-wallet transactions.
I need to call gettransaction. I looked in the header and found the gettransaction function. I use this and don't get the expected result, because in the code getrawtransaction call used. this is an example of a poorly designed library. spagetti-style

**Comment by DanielZorin** [comment]
Ok, let's rename it to getanddecoderawtransaction or something like that.

**Comment by DanielZorin** [comment]
And return the original gettransaction that reproduced bitcoin's gettransaction call

**Comment by corvaxx** [comment]
sorry, I thought a little deeper. it works, but without checking utxo, tx output, returned via getrawtransaction, may be invalid. 
gettxout in this case returns null. this is the main difference between gettxout and get()transaction. 
but need to restore the original gettransaction

**Pull request merged**
